### ISSUE TITLE
Error when previewing single product

### ISSUE THREAD

**Issue by WinsleyJ** [thriveweb/wooswipe#49]
I’m getting the following error when trying to preview a productpage:

```
Warning: Undefined variable $featuredArray in /plugins/wooswipe/wooswipe.php on line 282

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /plugins/wooswipe/wooswipe.php:282 
Stack trace: #0 /plugins/wooswipe/wooswipe.php(282): array_merge(NULL, Array) 
#1 /wp-includes/class-wp-hook.php(307): wooswipe_woocommerce_show_product_thumbnails('') 
#2 /wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) 
#3 /wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#4 /plugins/woocommerce/templates/content-single-product.php(43): do_action('woocommerce_bef...') 
#5 /wp-includes/template.php(772): require('/app/sites/...') 
#6 /plugins/woocommerce/includes/wc-core-functions.php(284): load_template('/app/sites/...', false) 
#7 /plugins/woocommerce/includes/wc-template-functions.php(971): wc_get_template_part('content', 'single-product') 
#8 /themes/Total/woocommerce.php(33): woocommerce_content() 
#9 /wp-includes/template-loader.php(106): include('/app/sites/...') 
#10 /wp-blog-header.php(19): require_once('/app/sites/...') 
#11 /index.php(5): require('/app/sites/...') #12 {main} thrown in /plugins/wooswipe/wooswipe.php on line 282
```

**Comment by deanoakley** [comment]
Maybe related to a product with no image https://plugins.thriveweb.com.au/product/test-product-with-no-image/

**Comment by WinsleyJ** [comment]
My bad, you're right!
